/* DOCTO ONLINE — condition database compiled from the Ayurveda KB (knowledge_base/) and
   Allopathy KB (allopathy_knowledge_base/) in this folder. All doses = adult OTC.
   flags on modern items: pcm=paracetamol, nsaid, decong=decongestant, antihist-sed, laxstim */
const DB = {

/* ---------- EMERGENCY RED FLAGS (keyword triggers on free text + engine checks) ---------- */
redFlagKeywords: [
 {k:["chest pain","chest pressure","chest tightness","seene me dard","seene mein dard"], id:"cardiac"},
 {k:["can't breathe","cannot breathe","breathless at rest","saans nahi","gasping","blue lips"], id:"breathing"},
 {k:["face droop","slurred speech","one side weak","arm weakness sudden","stroke"], id:"stroke"},
 {k:["worst headache","thunderclap"], id:"headache_worst"},
 {k:["stiff neck fever","neck stiffness with fever"], id:"meningitis"},
 {k:["vomiting blood","blood in vomit","khoon ki ulti","coffee ground"], id:"gi_bleed"},
 {k:["black stool","blood in stool","khooni dast"], id:"gi_bleed"},
 {k:["coughing blood","blood in cough","khoon wali khansi"], id:"hemoptysis"},
 {k:["blood in urine","peshab me khoon"], id:"hematuria"},
 {k:["seizure","fit aaya","convulsion"], id:"seizure"},
 {k:["unconscious","fainted and not waking","behosh"], id:"unconscious"},
 {k:["suicide","end my life","khudkushi","self harm"], id:"crisis"},
 {k:["throat swelling","tongue swelling","anaphylaxis"], id:"anaphylaxis"},
 {k:["pregnant bleeding","pregnancy bleeding"], id:"preg_bleed"},
 {k:["severe abdominal pain","pet me bahut tez dard","rigid abdomen"], id:"acute_abdomen"},
 {k:["snake bite","poison","overdose","zeher"], id:"poison"},
 {k:["testicle sudden pain"], id:"torsion"}
],
emergencyAdvice: {
 cardiac:"Chest pain/pressure — especially with sweating, breathlessness, or pain spreading to arm/jaw — can be a heart attack.",
 breathing:"Severe difficulty breathing needs emergency care now.",
 stroke:"Face drooping, arm weakness or slurred speech are stroke signs. Every minute matters.",
 headache_worst:"A sudden 'worst-ever' headache needs an emergency scan.",
 meningitis:"Fever with a stiff neck (± rash/confusion) can be meningitis.",
 gi_bleed:"Vomiting blood or black/bloody stools means internal bleeding.",
 hemoptysis:"Coughing up blood needs urgent evaluation.",
 hematuria:"Visible blood in urine needs urgent evaluation.",
 seizure:"A first or prolonged seizure is an emergency.",
 unconscious:"Unresponsiveness is an emergency.",
 crisis:"You matter. Please reach out right now — call a suicide-prevention helpline (India: 9152987821 / Tele-MANAS 14416) or go to the nearest emergency room. You don't have to face this alone.",
 anaphylaxis:"Swelling of lips/tongue/throat or hives with breathlessness is anaphylaxis. Use an adrenaline pen if available.",
 preg_bleed:"Bleeding or severe pain in pregnancy needs emergency obstetric care.",
 acute_abdomen:"Severe or rigid abdominal pain can be appendicitis/obstruction.",
 poison:"Suspected poisoning/overdose/bite — emergency now. Do not induce vomiting.",
 torsion:"Sudden severe testicular pain is an emergency (torsion)."
},

/* ---------- LAB REFERENCE RANGES for report OCR parsing ---------- */
labTests: [
 {key:"hb", names:["haemoglobin","hemoglobin","hb"], unit:"g/dL", low:12, high:17.5,
  lowMsg:"Low haemoglobin → anaemia. Iron-rich diet; doctor should find the cause. Ayurveda: amla, pomegranate, black raisins, Dhatri Lauha/Punarnavadi Mandura (practitioner).",
  highMsg:"High haemoglobin — recheck; can be dehydration or other causes; discuss with a doctor."},
 {key:"wbc", names:["total leucocyte","total leukocyte","tlc","wbc count","white blood cell"], unit:"/µL", low:4000, high:11000,
  lowMsg:"Low white cells — viral infection or other causes; doctor review.",
  highMsg:"Raised white cells suggests infection/inflammation — a doctor should correlate; antibiotics only on prescription."},
 {key:"platelet", names:["platelet"], unit:"/µL", low:150000, high:450000,
  lowMsg:"LOW PLATELETS — if you have fever, rule out dengue urgently. Below 100,000 → hospital NOW. Hydrate well; avoid ibuprofen/aspirin.",
  highMsg:"High platelets — usually reactive; doctor review."},
 {key:"glucose_f", names:["fasting blood sugar","fasting glucose","fbs","glucose fasting","glucose - fasting"], unit:"mg/dL", low:60, high:100,
  lowMsg:"Low fasting sugar — if on diabetes medicines, review dosing with your doctor.",
  highMsg:"Fasting sugar above 100 (≥126 = diabetes range). See a physician; begin diet control, daily walking. Ayurveda support: bitter gourd, fenugreek, amla+turmeric (Nishamalaki), gudmar — inform your doctor (they add to medicines' effect)."},
 {key:"glucose_pp", names:["post prandial","postprandial","ppbs","pp sugar"], unit:"mg/dL", low:70, high:140,
  lowMsg:"Low post-meal sugar — review with doctor.",
  highMsg:"Post-meal sugar high (≥200 = diabetes range) — physician consult for confirmation and plan."},
 {key:"hba1c", names:["hba1c","glycated","glycosylated"], unit:"%", low:4, high:5.7,
  lowMsg:"HbA1c low — usually fine.",
  highMsg:"HbA1c raised: 5.7–6.4 = prediabetes; ≥6.5 = diabetes. See a physician; lifestyle change works best started early."},
 {key:"tsh", names:["tsh","thyroid stimulating"], unit:"µIU/mL", low:0.4, high:4.5,
  lowMsg:"TSH low — possible overactive thyroid; see a physician/endocrinologist.",
  highMsg:"TSH high — possible underactive thyroid; see a physician/endocrinologist. Ayurveda adjunct: kanchanara guggulu (practitioner)."},
 {key:"creatinine", names:["creatinine"], unit:"mg/dL", low:0.6, high:1.3,
  lowMsg:"Low creatinine — usually not significant.",
  highMsg:"Raised creatinine → kidney function needs medical review. Avoid painkillers like ibuprofen; hydrate; see a physician soon."},
 {key:"sgpt", names:["sgpt","alt","alanine"], unit:"U/L", low:0, high:45,
  lowMsg:"", highMsg:"Raised SGPT/ALT → liver stress. Stop alcohol, review medicines; physician check. Ayurveda support: bhumyamalaki, kutki, Arogyavardhani (practitioner)."},
 {key:"sgot", names:["sgot","ast","aspartate"], unit:"U/L", low:0, high:40,
  lowMsg:"", highMsg:"Raised SGOT/AST → liver stress; physician review."},
 {key:"bilirubin", names:["bilirubin total","total bilirubin","bilirubin"], unit:"mg/dL", low:0.1, high:1.2,
  lowMsg:"", highMsg:"Raised bilirubin → jaundice range. Physician review; avoid alcohol/fried food; hydrate."},
 {key:"crp", names:["crp","c-reactive"], unit:"mg/L", low:0, high:6,
  lowMsg:"", highMsg:"Raised CRP = active inflammation/infection somewhere; correlate with symptoms; doctor review."},
 {key:"esr", names:["esr","erythrocyte sedimentation"], unit:"mm/hr", low:0, high:20,
  lowMsg:"", highMsg:"Raised ESR = inflammation; non-specific; doctor correlation."},
 {key:"vitd", names:["vitamin d","25-oh","25 oh"], unit:"ng/mL", low:30, high:100,
  lowMsg:"Vitamin D low — sunlight 20 min/day; doctor may prescribe weekly D3 60,000 IU (take after a fatty meal).",
  highMsg:"Vitamin D very high — stop supplements, doctor review."},
 {key:"b12", names:["vitamin b12","b12","cobalamin"], unit:"pg/mL", low:200, high:900,
  lowMsg:"B12 low — supplements help (after food); vegetarians: milk/curd/fortified foods; doctor may give injections.",
  highMsg:"B12 high — usually supplement effect."},
 {key:"cholesterol", names:["total cholesterol"], unit:"mg/dL", low:100, high:200,
  lowMsg:"", highMsg:"Total cholesterol high — diet (less fried/refined), 30-min daily walk; physician for risk assessment. Ayurveda: guggul preparations, garlic, triphala at night."},
 {key:"ldl", names:["ldl"], unit:"mg/dL", low:0, high:100,
  lowMsg:"", highMsg:"LDL above optimal — lifestyle + physician review (statin decision is a doctor's call)."},
 {key:"hdl", names:["hdl"], unit:"mg/dL", low:40, high:100,
  lowMsg:"HDL low — exercise raises it.", highMsg:""},
 {key:"tg", names:["triglyceride"], unit:"mg/dL", low:0, high:150,
  lowMsg:"", highMsg:"Triglycerides high — cut sugar/alcohol/fried food; exercise; physician review."},
 {key:"uric", names:["uric acid"], unit:"mg/dL", low:2.5, high:7,
  lowMsg:"", highMsg:"Uric acid high → gout risk. Hydrate, limit red meat/alcohol/sugary drinks. Ayurveda: kaishore guggulu, giloy. Physician if joint attacks."},
 {key:"sodium", names:["sodium","na+"], unit:"mEq/L", low:135, high:145,
  lowMsg:"Low sodium — needs medical review (esp. elderly).", highMsg:"High sodium — hydration/medical review."},
 {key:"potassium", names:["potassium","k+"], unit:"mEq/L", low:3.5, high:5.1,
  lowMsg:"Low potassium — doctor review.", highMsg:"High potassium — urgent doctor review (heart rhythm risk)."},
 {key:"urine_pus", names:["pus cells","pus cell"], unit:"/hpf", low:0, high:5,
  lowMsg:"", highMsg:"Pus cells in urine → urine infection likely. See a doctor for a short antibiotic course; drink plenty of water. (Matches UTI plan.)"}
],
labQualitative: [
 {key:"dengue", names:["dengue ns1","ns1 antigen","dengue igm"], posMsg:"DENGUE POSITIVE → see a doctor today. Hydrate aggressively (ORS/coconut water), paracetamol ONLY (never ibuprofen/aspirin), daily platelet monitoring. Hospital if bleeding, severe abdominal pain, drowsiness, or platelets fall below 100,000. Papaya-leaf extract is a traditional adjunct."},
 {key:"malaria", names:["malaria","mp smear","malarial parasite"], posMsg:"MALARIA POSITIVE → physician today for prescription anti-malarials (self-treatment is unsafe). Paracetamol for fever, fluids. Giloy/sudarshan churna only as adjunct."},
 {key:"widal", names:["widal"], posMsg:"Widal suggestive of TYPHOID → physician for antibiotics. Soft light diet, hydration, full medicine course essential."},
 {key:"covid", names:["covid","sars-cov"], posMsg:"COVID positive → isolate per guidance, rest, fluids, paracetamol; monitor oxygen (SpO2 <94% → hospital). High-risk persons: contact doctor early."},
 {key:"urine_nitrite", names:["nitrite"], posMsg:"Urine nitrite positive → bacterial urine infection; doctor for antibiotics; hydrate well."}
],

/* ---------- TEST RULES: when the bot recommends investigations ---------- */
testRules: [
 {when:"fever>3d", tests:["CBC (complete blood count)","Dengue NS1 + IgM (in season/area)","Malaria smear/antigen","Typhoid (blood culture/Widal)"], why:"Fever beyond 3 days should be tested, not guessed."},
 {when:"fever_high", tests:["CBC","Dengue NS1","Malaria antigen"], why:"Temperature ≥103°F needs a cause."},
 {when:"uti", tests:["Urine routine & microscopy","Urine culture (if recurrent)"], why:"Confirms infection before antibiotics."},
 {when:"injury", tests:["X-ray of the injured part"], why:"To rule out a fracture if you can't bear weight / severe swelling."},
 {when:"chronic_fatigue", tests:["CBC","TSH (thyroid)","Fasting sugar","Vitamin D & B12"], why:"Common hidden causes of tiredness."},
 {when:"acidity_chronic", tests:["Doctor review ± endoscopy (doctor decides)","H. pylori test (doctor)"], why:"Heartburn >2 weeks or with warning signs must be scoped, not silenced."},
 {when:"diarrhea_persist", tests:["Stool routine & culture"], why:"Diarrhea beyond 3–4 days or with blood needs a stool test."},
 {when:"joint_chronic", tests:["Uric acid","ESR/CRP","RA factor (doctor)"], why:"To separate gout / inflammatory arthritis / wear-and-tear."},
 {when:"headache_chronic", tests:["Eye check (refraction)","BP measurement","Doctor review ± imaging (doctor decides)"], why:"Frequent headaches need cause-hunting."},
 {when:"anemia_suspect", tests:["CBC","Ferritin (iron stores)"], why:"Pallor/fatigue/heavy periods point to anaemia."},
 {when:"sugar_suspect", tests:["Fasting & post-meal sugar","HbA1c"], why:"Excess thirst/urination/tiredness screens for diabetes."},
 {when:"cough3w", tests:["Chest X-ray","Sputum test (doctor)"], why:"Any cough beyond 3 weeks must be X-rayed (TB/other causes)."}
],

/* ---------- CONDITIONS ---------- */
/* modern[]: {t:text, f?:flag}  flags: nsaid, pcm, decong, sed(antihistamine sedating), lax_stim */
conds: [

{id:"fever", nm:"Fever (viral)", al:["fever","bukhar","temperature","viral","body hot","jwar"],
 sys:"general", doctor:"General physician",
 dq:[{q:"Any of these along with fever?",opts:["Severe body/joint ache","Rash or red spots","Chills & sweating cycles","Burning urine","Sore throat/cold","None of these"]}],
 modern:[
  {t:"Paracetamol 500–650 mg — 1 tablet when temperature >100°F or for aches; repeat only after 6 hours; MAX 4 doses/day. After food preferably.", f:"pcm"},
  {t:"Sponge forehead/armpits with room-temperature water (not ice) if very hot."},
  {t:"Fluids: 2.5–3 L/day — water, ORS, coconut water, soups. Rest fully."},
  {t:"Do NOT take antibiotics on your own — most fevers are viral and they don't help."}],
 ayur:[
  "Tulsi-ginger-black pepper kadha (decoction) with honey, twice daily.",
  "Sudarshan churna 3 g with water twice daily (classical all-fever formula) OR Sitopaladi churna 1/2 tsp with honey if cough/cold type.",
  "Giloy (guduchi) juice 10–15 ml or tablet twice daily — esp. for lingering/low-grade fever.",
  "Light diet only while feverish: moong dal khichdi, rice gruel; no heavy/fried/dairy-rich food (ama principle). Rest = medicine."],
 tests:["fever>3d","fever_high"],
 seeDoc:["Fever lasting more than 3 days","Temperature ≥103°F not settling with paracetamol","Fever with burning urine, ear pain, severe throat pain (needs source check)","Any fever in infants, elderly, pregnancy, diabetes"],
 emerg:["Stiff neck, rash that doesn't fade on pressure, confusion or fits","Breathlessness or chest pain","Signs of dehydration (very little urine, drowsiness)"]},

{id:"cold", nm:"Common cold", al:["cold","runny nose","blocked nose","sneezing","jukam","zukam","nazla","coryza"],
 sys:"resp", doctor:"General physician / ENT",
 dq:[{q:"What's the mucus like?",opts:["Clear & watery","Thick yellow/green","Mostly blocked, little mucus"]}],
 modern:[
  {t:"A cold is viral — it clears on its own in about a week. The goal is comfort, not a pile of pills: rest and plenty of warm fluids do most of the work."},
  {t:"First-line (safest and genuinely effective): steam inhalation 2–3×/day, saline nasal drops, and a warm salt-water gargle if the throat is scratchy."},
  {t:"Add a medicine ONLY if a symptom is really bothering you — and just the one that fits: paracetamol 500–650 mg after food for body ache or mild fever (max 4/day).", f:"pcm"},
  {t:"…or cetirizine 10 mg at night, only if a runny nose/sneezing is the main problem (may cause mild drowsiness).", f:"sed"},
  {t:"Please avoid antibiotics (useless against a cold) and don't stack several cold/decongestant products together."}],
 ayur:[
  "Classic kadha: tulsi 5 leaves + ginger + 4 black peppercorns boiled, add honey when warm — 2–3×/day.",
  "Turmeric milk (haldi doodh) at bedtime.",
  "Sitopaladi churna 1/2 tsp with honey 2–3×/day.",
  "Steam with ajwain or eucalyptus; avoid curd, cold drinks, fridge food till clear. Anu taila 2 drops/nostril in the morning prevents recurrent colds."],
 tests:[],
 seeDoc:["Not improving after 10 days or worsening after initial improvement","Facial pain/pressure with thick discharge (sinusitis)","Ear pain develops","High fever"],
 emerg:["Breathlessness or wheezing","Drowsiness/confusion"]},

{id:"cough", nm:"Cough", al:["cough","khansi","khaansi","coughing"],
 sys:"resp", doctor:"General physician / pulmonologist if persistent",
 dq:[{q:"Which type fits best?",opts:["Dry, tickly cough","Wet cough with phlegm","Cough mainly at night","Cough with wheeze/whistling"]},
     {q:"Phlegm colour (if any)?",opts:["White/clear","Yellow/green","Blood-streaked","No phlegm"]}],
 modern:[
  {t:"Dry cough: honey 1 tsp in warm water 3×/day (not for infants <1 yr); dextromethorphan syrup at night if sleep is broken.", f:""},
  {t:"Wet cough: DO NOT suppress. Guaifenesin (expectorant) syrup after food + plenty of warm fluids + steam 2–3×/day."},
  {t:"Paracetamol after food if throat/chest soreness.", f:"pcm"},
  {t:"Avoid smoke/dust; sleep with head slightly raised."}],
 ayur:[
  "Sitopaladi or Talisadi churna 1/2 tsp with honey thrice daily — the classical cough powders.",
  "Fresh ginger juice 1 tsp + honey 1 tsp, 3×/day (dry cough); tulsi juice with honey for children >1 yr.",
  "Vasaka (Adhatoda) syrup/juice 10 ml twice daily — for wet cough.",
  "Black pepper + rock candy + ghee paste licked slowly for throat tickle; avoid cold/fried food, curd at night."],
 tests:["cough3w"],
 seeDoc:["Cough beyond 3 weeks (needs chest X-ray — TB must be ruled out)","Yellow-green phlegm with fever/breathlessness (possible chest infection — antibiotics are a doctor's call)","Wheeze — may need an inhaler (prescription)","Night cough with acidity (reflux) or weight loss"],
 emerg:["Coughing up blood","Breathless at rest / lips turning blue","Chest pain with breathing"]},

{id:"sore_throat", nm:"Sore throat", al:["sore throat","throat pain","gala kharab","gale me dard","kharash","pharyngitis","tonsil"],
 sys:"resp", doctor:"ENT / General physician",
 dq:[{q:"Look with a torch — what do you see/feel?",opts:["Just red/scratchy","White patches/pus on tonsils","High fever + swollen neck glands","Hoarse voice mainly"]}],
 modern:[
  {t:"Warm salt-water gargle (1/2 tsp salt in a glass) 4–5×/day — the single best home measure."},
  {t:"Paracetamol 500–650 mg after food for pain/fever, max 4/day; OR ibuprofen 400 mg after food if not contraindicated.", f:"pcm"},
  {t:"Medicated lozenges / benzydamine spray for local relief; warm fluids, rest the voice."},
  {t:"White patches + fever + tender glands + NO cough → likely strep; a doctor should examine — that's the case where antibiotics genuinely help."}],
 ayur:[
  "Turmeric + salt warm-water gargle 3×/day.",
  "Khadiradi vati — suck 1 tablet 3–4×/day (classical throat pill).",
  "Licorice (mulethi) small piece to suck, or licorice + honey tea.",
  "Sitopaladi with honey; avoid cold drinks, curd, pickles till healed."],
 tests:[],
 seeDoc:["Pus/white patches with high fever (strep test/antibiotics)","Not improving in 3–4 days","Recurrent tonsillitis (ENT opinion)","Hoarseness beyond 3 weeks"],
 emerg:["Cannot swallow even saliva / drooling","Difficulty breathing or muffled voice","Swelling of one side of throat/neck (abscess)"]},

{id:"flu", nm:"Flu (influenza)", al:["flu","influenza","body ache fever","viral with body pain"],
 sys:"resp", doctor:"General physician",
 modern:[
  {t:"Rest + fluids aggressively (this IS the treatment; it runs ~1 week)."},
  {t:"Paracetamol 650 mg after food every 6–8 h for fever/aches (max 4/day).", f:"pcm"},
  {t:"Steam + saline for congestion; honey-lemon warm water for throat/cough."},
  {t:"High-risk persons (elderly, pregnant, diabetic, lung/heart disease): see a doctor within 48 h — a prescription antiviral (oseltamivir) works best started early."}],
 ayur:["Sudarshan churna or Sanjivani vati (250 mg, with warm water) twice daily for viral fevers (adjunct).","Tulsi-ginger-pepper-cinnamon kadha 2–3×/day.","Chyawanprash 1 tsp with warm milk during recovery to rebuild strength.","Complete rest; light khichdi diet; no cold water/bathing chills."],
 tests:["fever>3d"],
 seeDoc:["High-risk person (get antiviral early)","Fever >3 days","Improving then suddenly worse (secondary infection)"],
 emerg:["Breathlessness, chest pain, confusion, blue lips","Not passing urine (dehydration)"]},

{id:"sinusitis", nm:"Sinusitis", al:["sinus","sinusitis","facial pressure","heavy head cold","cheek pain nose"],
 sys:"resp", doctor:"ENT",
 modern:[
  {t:"Steam inhalation 3×/day + saline nasal rinse — mainstay."},
  {t:"Oxymetazoline nasal spray max 3 days for blockage.", f:"decong"},
  {t:"Paracetamol/ibuprofen after food for facial pain.", f:"pcm"},
  {t:"Most sinusitis is viral and clears in 2–3 weeks without antibiotics; >10 days or worsening → doctor (may prescribe antibiotics/steroid spray)."}],
 ayur:["Anu taila or Shadbindu taila nasya: 2 drops each nostril morning (after steam) — the classical sinus therapy.","Trikatu (ginger-pepper-pippali) 1/2 tsp with honey twice daily to melt mucus.","Chitraka-haritaki avaleha 1 tsp twice daily (classical sinusitis formula).","Avoid curd, cold food/drinks, day-sleep; ajwain-steam."],
 tests:[], seeDoc:["Symptoms >10 days or getting worse","High fever with severe one-sided face pain","Recurrent sinusitis (ENT for scan)"],
 emerg:["Swelling/redness around an eye, vision change, severe headache with vomiting"]},

{id:"hayfever", nm:"Allergy / hay fever", al:["allergy","hay fever","dust allergy","pollen","allergic rhinitis","sneezing morning","itchy eyes nose"],
 sys:"resp", doctor:"ENT / Allergist",
 modern:[
  {t:"Cetirizine 10 mg or loratadine 10 mg once daily (loratadine = non-drowsy).", f:""},
  {t:"Identify & avoid trigger (dust/pollen/pet); wash bedding hot weekly; masks help."},
  {t:"Saline nasal rinse daily; steroid nasal spray (fluticasone) once daily is the best preventer for persistent symptoms — start early in season."},
  {t:"Antihistamine eye drops for itchy eyes."}],
 ayur:["Anu taila nasya 2 drops/nostril daily — builds nasal resistance.","Haridra khanda 1 tsp with warm milk twice daily — the classical anti-allergy formula.","Local raw honey 1 tsp daily; giloy for immune balance.","Neti (saline wash) if trained; avoid curd at night, cold exposure."],
 tests:[], seeDoc:["Not controlled with the above","Wheeze/night cough (asthma check)","For allergy testing"],
 emerg:["Any throat/tongue swelling or breathlessness after exposure/food → emergency (anaphylaxis)"]},

{id:"earache", nm:"Ear pain / infection", al:["ear pain","earache","kaan dard","kan me dard","ear infection","ear blocked"],
 sys:"ent", doctor:"ENT",
 dq:[{q:"Which fits?",opts:["Pain after cold, inside ear","Itchy outer ear, worse on pulling","Blocked feeling/wax","Discharge from ear"]}],
 modern:[
  {t:"Paracetamol or ibuprofen after food — pain relief is the mainstay for 2–3 days (many middle-ear infections settle).", f:"pcm"},
  {t:"Warm (not hot) compress against the ear."},
  {t:"Wax: olive oil drops 2–3 drops twice daily for 3–4 days to soften; NEVER cotton buds."},
  {t:"Do not pour random drops if there's discharge (drum may be perforated) — doctor first."}],
 ayur:["Warm compress; 2 drops of slightly warmed sesame oil ONLY if no discharge and drum intact (skip if unsure).","Bilwadi taila (classical ear oil) — use only under guidance.","Treat the cold alongside (steam, kadha) since ear pain often follows it."],
 tests:[], seeDoc:["Pain >2–3 days or worsening / discharge appears","Child with high fever or both ears","Hearing reduced after episode","Recurrent infections"],
 emerg:["Swelling/redness BEHIND the ear","Sudden complete hearing loss","Severe dizziness or facial weakness"]},

{id:"headache", nm:"Headache (tension)", al:["headache","sir dard","sar dard","head pain","sardard"],
 sys:"neuro", doctor:"General physician / Neurologist if frequent",
 dq:[{q:"Which pattern fits best?",opts:["Band-like/both sides, stress or screen related","One-sided throbbing with nausea/light sensitivity (migraine-like)","With blocked nose/face pressure","Started after missing sleep/meals/water"]}],
 modern:[
  {t:"Paracetamol 650 mg OR ibuprofen 400 mg after food at onset (don't use painkillers >10 days/month — causes rebound headache).", f:"pcm"},
  {t:"Water 2 glasses now (dehydration is a top cause); eat if meals were missed."},
  {t:"20-min screen breaks, neck stretches, warm compress on neck/shoulders; regular sleep."},
  {t:"Get eyes tested if frequent (refraction headache); check BP once."}],
 ayur:["Warm sesame-oil head & foot massage before bath; shirodhara series for chronic stress headaches.","Brahmi or jatamansi tea in the evening; brahmi ghee 1/2 tsp in warm milk at night.","Pitta type (burning, worse in sun): sandalwood paste on forehead, amla juice morning.","Kapha type (heavy, morning, with congestion): ginger paste on forehead, trikatu with honey, skip one meal."],
 tests:["headache_chronic"],
 seeDoc:["More than 1–2 headaches/week or need painkillers often","Migraine pattern (a doctor can prescribe faster-acting specific medicines — triptans — and preventives)","Headache changing pattern"],
 emerg:["Sudden worst-ever/thunderclap headache","With fever + stiff neck or rash","With weakness/slurred speech/vision loss","After head injury","New headache with vomiting on waking"]},

{id:"migraine", nm:"Migraine", al:["migraine","adha sir dard","one side headache","aadha sar"],
 sys:"neuro", doctor:"Neurologist",
 modern:[
  {t:"Treat EARLY at first sign: ibuprofen 400 mg (after food) or paracetamol 1000 mg + rest in a dark quiet room.", f:"nsaid"},
  {t:"For nausea: domperidone (pharmacist) before food helps the painkiller absorb too."},
  {t:"Cold pack on forehead; caffeine (one strong tea/coffee) can help if taken early."},
  {t:"If attacks are moderate/severe or frequent (>1/month): a doctor can prescribe triptans (fast-acting) and daily preventives — very effective, worth the visit."}],
 ayur:["Keep a trigger diary (sleep loss, skipped meals, specific foods, sun) — trigger avoidance is half the cure.","Shirodhara course; nasya with shadbindu taila 2 drops each nostril in the morning during clusters.","Brahmi + ashwagandha 1/2 tsp each with milk at night for stress-linked migraine.","During attack: dark room, ginger tea for nausea, cold sandalwood paste on forehead."],
 tests:["headache_chronic"],
 seeDoc:["First severe migraine (confirm diagnosis)","Frequent attacks — preventive treatment exists","Aura lasting >1 hour"],
 emerg:["'Worst ever' or abrupt-onset headache","Aura with limb weakness or speech difficulty (stroke mimic)"]},

{id:"acidity", nm:"Acidity / heartburn", al:["acidity","heartburn","acid reflux","gerd","seene me jalan","khatti dakar","sour burp","chest burning after food"],
 sys:"digestive", doctor:"Gastroenterologist if persistent",
 dq:[{q:"When does it burn most?",opts:["After spicy/heavy/late meals","On lying down at night","Empty stomach mornings","Almost daily regardless"]}],
 modern:[
  {t:"Immediate: antacid gel/tablet (e.g., Gelusil/Digene) after meals & at bedtime, as needed."},
  {t:"Frequent (≥2×/week): omeprazole 20 mg once daily 30 min BEFORE breakfast for 14 days max OTC; if still needed → doctor."},
  {t:"Gaviscon-type alginate after dinner if night reflux."},
  {t:"Fixes that matter: dinner 3 h before bed, raise head-end of bed 4–6 in, smaller meals, cut trigger (spicy/fried/citrus/tea-coffee excess/alcohol/smoking), lose belly weight."}],
 ayur:["Amla powder 1 tsp with water morning empty stomach, or amla juice 20 ml — the prime Pitta remedy.","Avipattikar churna 1/2–1 tsp with water before lunch & dinner (classical acidity formula).","Shatavari 1/2 tsp with milk twice daily for burning; licorice tea for gnawing empty-stomach burn (skip if BP high).","Cold milk sips or soaked raisins for quick relief; avoid curd at night, excess pickle/papad; don't lie down straight after meals."],
 tests:["acidity_chronic"],
 seeDoc:["Symptoms >2 weeks despite the above (needs proper evaluation — possibly endoscopy/H. pylori test)","Age >50 with new symptoms","On daily painkillers (they cause gastritis)"],
 emerg:["Difficulty/pain swallowing, food sticking","Vomiting blood / black stools","Unintentional weight loss","Chest pain with sweating/breathlessness — treat as HEART until proven otherwise"]},

{id:"indigestion", nm:"Indigestion / gas / bloating", al:["gas","bloating","indigestion","pet phoolna","badhazmi","apach","burping","farting","flatulence","pet me gas"],
 sys:"digestive", doctor:"General physician",
 modern:[
  {t:"Simethicone (anti-gas) after meals as needed; antacid if burning too."},
  {t:"Eat slowly, smaller meals; skip fizzy drinks, gum; walk 10–15 min after meals."},
  {t:"Note trigger foods (beans, cabbage-family, excess dairy if lactose-intolerant) and moderate them."},
  {t:"If bloating is persistent/daily for >2–3 weeks → doctor (rule out other causes)."}],
 ayur:["Hing (asafoetida) pinch + black salt in warm water for gas colic; or ajwain 1/2 tsp + black salt chewed with warm water.","Hingwastak churna 1/2 tsp with first bite of ghee-rice/lunch — the classical gas formula.","Fresh ginger slice + rock salt + lemon before meals kindles agni.","Jeera-saunf-ajwain water through the day; triphala 1 tsp at night if evacuation incomplete.","Buttermilk with roasted jeera after lunch (not at night)."],
 tests:[], seeDoc:["Persistent daily bloating >2–3 weeks","With weight loss or appetite loss","New symptoms after 50"],
 emerg:["Severe pain with vomiting and no gas/stool passing (obstruction)","Pain with rigid hard abdomen"]},

{id:"diarrhea", nm:"Diarrhea (loose motions)", al:["diarrhea","loose motion","dast","loose stools","patli latrine","stomach upset motion"],
 sys:"digestive", doctor:"General physician",
 dq:[{q:"Any of these?",opts:["Watery only","With vomiting too","Blood or mucus in stool","After outside/street food","More than 8–10 motions/day"]}],
 modern:[
  {t:"ORS after EVERY loose motion — this is the real treatment. (1 sachet in 1 L clean water; sip through the day.) Homemade: 6 tsp sugar + 1/2 tsp salt in 1 L."},
  {t:"Zinc 20 mg once daily × 10–14 days (esp. children — WHO standard, shortens illness)."},
  {t:"Eat light but EAT: khichdi, curd-rice, banana, toast. Avoid milk (except curd), fried, very sweet."},
  {t:"Loperamide 2 mg after a loose stool (max 4 tabs/day, ≤2 days) ONLY for adult convenience travel — NEVER if fever or blood in stool.", f:""},
  {t:"Probiotic sachet/capsule daily can shorten it."}],
 ayur:["Bael (wood apple) pulp or bael murabba — the classical binder; or unripe bael powder 1 tsp with water twice daily.","Nutmeg (jaiphal) paste a pinch with buttermilk twice daily; pomegranate juice/peel decoction sips.","Kutajarishta 15 ml with equal water after meals twice daily (classical, esp. if recurrent/dysentery-type).","Buttermilk with roasted cumin + rock salt is both food & medicine (takra)."],
 tests:["diarrhea_persist"],
 seeDoc:["Beyond 3–4 days","Recurrent episodes (stool test)","Recent antibiotic use","Diabetic/elderly early"],
 emerg:["Blood in stool or high fever with motions","Signs of dehydration: very little/dark urine, dizziness, sunken eyes, drowsiness (esp. children/elderly)","Severe continuous abdominal pain"]},

{id:"constipation", nm:"Constipation", al:["constipation","kabz","qabz","hard stool","pet saaf nahi","motion problem"],
 sys:"digestive", doctor:"General physician",
 modern:[
  {t:"Fibre up: 2 fruits + 2 veg servings + whole grains daily; Isabgol (psyllium) 1–2 tsp in warm water/milk at bedtime — first-line and safe."},
  {t:"Water 8+ glasses/day; 30-min daily walk; fixed toilet time after breakfast, don't suppress the urge."},
  {t:"If needed: lactulose 15 ml at night (gentle, safe). Stimulants (senna/bisacodyl) only occasionally, ≤1 week.", f:"lax_stim"},
  {t:"NEVER take laxatives if there's abdominal pain + vomiting (obstruction risk), and not in pregnancy without advice."}],
 ayur:["Triphala churna 1 tsp in warm water at bedtime — the gold-standard bowel rejuvenator (safe long-term at low dose).","1 tsp cow ghee in a cup of warm milk at bedtime — classic for dry/Vata constipation.","Soaked raisins/figs (6–8 overnight) in the morning; papaya daily.","Castor oil 2 tsp in warm milk once at night for stubborn episodes (not routine, not in pregnancy).","Abhyanga (oil massage) + squatting position help chronic cases."],
 tests:[], seeDoc:["No relief in 2 weeks despite the above","Alternating constipation-diarrhea","Needs laxatives constantly"],
 emerg:["Blood in stool / black stool","Constipation with severe pain + vomiting + bloating (obstruction)","New-onset after age 50 with weight loss"]},

{id:"vomiting", nm:"Nausea / vomiting", al:["vomiting","ulti","nausea","jee michlana","matli","throwing up"],
 sys:"digestive", doctor:"General physician",
 modern:[
  {t:"Sip ORS/clear fluids in SMALL frequent sips (large gulps re-trigger); suck ice chips if needed."},
  {t:"Once settled 1–2 h: bland food (toast, banana, khichdi); avoid oily/spicy/milk for a day."},
  {t:"Ginger: tea/candy — genuine anti-nausea evidence; safe in pregnancy.","f":""},
  {t:"If travel-related: take an anti-motion tablet (dimenhydrinate/meclizine) 30–60 min BEFORE travel next time.", f:"sed"},
  {t:"Persistent vomiting → doctor can prescribe effective antiemetics (domperidone/ondansetron) — don't struggle beyond 24 h."}],
 ayur:["Ginger juice 1/2 tsp + honey licked slowly; or cardamom powder pinch with honey.","Lemon + mint water sips; smell of lemon/mint reduces nausea.","Rice water (thin gruel) as first food re-entry.","For acidity-type vomiting: cold milk sips, amla."],
 tests:[], seeDoc:["Vomiting >24 h or can't keep any fluid down","Diabetic who can't eat (sugar risk)","Vomiting during pregnancy that prevents eating"],
 emerg:["Blood or 'coffee-grounds' in vomit","Green (bile) vomit with severe pain/bloating","With severe headache/stiff neck or after head injury","Signs of dehydration"]},

{id:"stomach_pain", nm:"Stomach pain / cramps", al:["stomach pain","pet dard","abdominal pain","pet me dard","stomach cramp","tummy ache"],
 sys:"digestive", doctor:"General physician",
 dq:[{q:"Where exactly is the pain?",opts:["Upper middle (burning — likely acidity)","Around navel, crampy with gas","Lower right side","Lower abdomen with urine burning","All over / can't localize"]}],
 modern:[
  {t:"Mild cramps/gas: warm water bag on abdomen, hing/simethicone; dicyclomine 10 mg (antispasmodic) after food if cramps persist (pharmacist)."},
  {t:"AVOID painkillers like ibuprofen for stomach pain (they irritate the stomach).", f:""},
  {t:"Light diet, ORS sips; watch pattern for 6–12 h."},
  {t:"Do NOT take a laxative or enema when in acute pain."}],
 ayur:["Ajwain 1/2 tsp + black salt with warm water (gas colic).","Hing dissolved in warm water applied around navel + a pinch orally.","Jeera-dhania-saunf tea after meals; ginger + lemon + rock salt before meals if appetite poor."],
 tests:[], seeDoc:["Pain recurring over days/weeks","Pain with fever","Pain related to periods (see period-pain plan)"],
 emerg:["Severe pain, or pain moving to lower-right abdomen with fever/vomiting (appendicitis)","Rigid, board-like abdomen","Pain with black stool/blood","Pain in pregnancy","Severe pain with no gas/stool passing"]},

{id:"piles", nm:"Piles (hemorrhoids)", al:["piles","hemorrhoid","bawaseer","bavasir","anal pain","blood while passing stool","fissure"],
 sys:"digestive", doctor:"General surgeon / proctologist",
 dq:[{q:"Which fits?",opts:["Bright red blood on wiping, painless","Painful lump at anus","Severe tearing pain with hard stool (fissure-like)","Itching mainly"]}],
 modern:[
  {t:"Fix constipation FIRST: isabgol at night, fibre, 8+ glasses water (see constipation plan)."},
  {t:"Warm sitz bath (sit in warm water) 10–15 min twice daily — best comfort measure."},
  {t:"OTC piles cream/suppository (lidocaine ± hydrocortisone) after motion & at night, ≤1 week.", f:""},
  {t:"Paracetamol for pain (avoid ibuprofen if bleeding).", f:"pcm"},
  {t:"Don't strain or sit long on the toilet; no phone in toilet."}],
 ayur:["Triphala 1 tsp at bedtime — keeps stool soft (core of classical treatment).","Buttermilk (takra) with roasted jeera + rock salt daily with lunch — THE classical piles remedy.","Abhayarishta 15–20 ml with equal water after meals twice daily.","Sitz bath with triphala decoction; coconut oil/jatyadi oil application for soothing.","Radish juice or cooked surana (elephant-foot yam) traditionally recommended; fissure-type: apply ghee + warm sitz."],
 tests:[], seeDoc:["Bleeding recurs beyond a week or heavy","Painful clotted lump (can be relieved quickly by a doctor)","Piles that come out and don't go back — procedures (banding etc.) are quick OPD fixes","Any bleeding + change in bowel habit or age >40 → colon check"],
 emerg:["Heavy continuous bleeding or dizziness","Black tarry stools"]},

{id:"uti", nm:"Urine infection (UTI)", al:["uti","urine infection","burning urine","peshab me jalan","frequent urination","urine burning"],
 sys:"urinary", doctor:"General physician / urologist if recurrent",
 dq:[{q:"Any of these too?",opts:["Fever/chills","Back/flank pain","Blood in urine","Just burning + frequency"]}],
 modern:[
  {t:"Water 3+ L through the day; don't hold urine; urinate after intercourse."},
  {t:"Urinary alkaliniser sachet (citrate) 2–3×/day for 2–3 days eases burning (skip if kidney disease).", f:""},
  {t:"Paracetamol for discomfort.", f:"pcm"},
  {t:"Most true UTIs need a SHORT PRESCRIPTION ANTIBIOTIC — quick fix, but a doctor must choose it. Get a urine routine test and see a physician if not clearly better in 24–48 h. Men, children, pregnant women: doctor from day 1."}],
 ayur:["Coriander-seed water (1 tsp soaked overnight, drink morning) — classical cooling diuretic.","Coconut water, barley water through the day.","Gokshura (Tribulus) churna 1 tsp with water twice daily, or Chandraprabha vati 1 tab twice daily (classical urinary formula).","Avoid spicy/oily food, tea/coffee excess, alcohol during episode."],
 tests:["uti"],
 seeDoc:["Symptoms >48 h despite fluids (antibiotics likely needed)","Recurrent UTIs (urine culture + urologist)","Diabetic, male, child, pregnant, elderly — see doctor immediately"],
 emerg:["Fever with chills + back/flank pain (kidney infection)","Blood in urine","Unable to pass urine at all"]},

{id:"period_pain", nm:"Period pain", al:["period pain","menstrual cramp","dysmenorrhea","period cramps","mahavari dard","periods me dard"],
 sys:"womens", doctor:"Gynaecologist",
 modern:[
  {t:"Mefenamic acid 500 mg OR ibuprofen 400 mg AFTER FOOD, started AS SOON AS pain begins (works far better early), every 8 h for 1–2 days.", f:"nsaid"},
  {t:"Hot water bag on lower abdomen/back; gentle walking/stretching."},
  {t:"If pain is severe every cycle → gynaecologist (very treatable; also rules out endometriosis)."}],
 ayur:["Ajwain 1/2 tsp + jaggery with warm water 2×/day during periods.","Warm sesame-oil massage on lower abdomen; rest with warmth.","Kumaryasava 15 ml with equal water after meals in the week before periods (cycle regulator) — avoid in pregnancy.","Ginger-cinnamon tea; avoid cold/raw food during periods; Shatavari 1/2 tsp with milk daily as a cycle tonic."],
 tests:[], seeDoc:["Severe pain every cycle or worsening over months","Pain with very heavy bleeding/clots","Pain outside periods too"],
 emerg:["Sudden severe one-sided lower abdominal pain (esp. if period missed — ectopic risk)","Fainting with heavy bleeding"]},

{id:"back_pain", nm:"Back pain", al:["back pain","kamar dard","lower back","backache","peeth dard"],
 sys:"musculo", doctor:"Orthopedician / physiotherapist",
 dq:[{q:"How did it start?",opts:["After lifting/bending/jerk","Gradually with sitting/posture","With leg pain/tingling below knee","After a fall/accident"]}],
 modern:[
  {t:"KEEP MOVING gently — bed rest beyond a day worsens it. Short walks every hour."},
  {t:"Ibuprofen 400 mg after food 2–3×/day for 3–5 days (with food; skip if ulcer/kidney issues) OR paracetamol 650 mg.", f:"nsaid"},
  {t:"Hot fomentation 15 min 2–3×/day; topical diclofenac gel on the sore band."},
  {t:"After 48–72 h: gentle stretches (knee-to-chest, cat-camel); fix chair/posture; core exercises prevent recurrence."}],
 ayur:["Warm Mahanarayana taila massage followed by hot fomentation (bag/hot towel), daily.","Yogaraja guggulu 1 tab twice daily after food (classical Vata-pain formula) for 1–2 weeks.","Ashwagandha 1/2 tsp with warm milk at night (strength + nerve tone).","Gentle yoga after acute phase: bhujangasana, marjari; avoid forward-bend lifting.","Kati basti (warm oil pooling therapy) at a panchakarma centre for recurring pain."],
 tests:["injury"],
 seeDoc:["Not improving in 1–2 weeks","Pain radiating below the knee with tingling/numbness (sciatica — needs assessment)","Recurrent episodes (physio program)"],
 emerg:["Numbness in the saddle/genital area, or new urine/stool control problems — EMERGENCY (nerve compression)","Back pain after significant fall/accident","With fever, or night pain + weight loss"]},

{id:"neck_pain", nm:"Neck pain / stiffness", al:["neck pain","gardan dard","stiff neck","cervical","neck stiffness"],
 sys:"musculo", doctor:"Orthopedician / physiotherapist",
 modern:[
  {t:"Keep gently mobile; avoid sudden jerks; thin pillow at proper height."},
  {t:"Ibuprofen 400 mg after food or paracetamol; topical gel.", f:"nsaid"},
  {t:"Hot fomentation 15 min 2–3×/day; screen at eye level, hourly breaks."},
  {t:"Gentle range-of-motion exercises after 48 h."}],
 ayur:["Warm sesame/Mahanarayana oil massage + hot towel daily.","Nasya (2 drops anu taila each nostril morning) — classical for neck/cervical issues.","Ashwagandha + milk at night; avoid cold draft on neck, day-sleep after meals.","Greeva basti at a panchakarma centre for chronic cervical pain."],
 tests:[], seeDoc:["Pain with arm tingling/numbness/weakness","Not improving in 1–2 weeks","Recurrent (posture/physio program)"],
 emerg:["Neck stiffness with FEVER + headache (meningitis)","After fall/accident","With weakness in limbs"]},

{id:"sprain", nm:"Sprain / muscle strain / minor injury", al:["sprain","twist","moch","strain","ankle twist","muscle pull","injury"],
 sys:"musculo", doctor:"Orthopedician",
 modern:[
  {t:"R.I.C.E for 48 h: Rest • Ice 20 min every 2–3 h (cloth-wrapped) • Compression (crepe bandage, snug not tight) • Elevation above heart level."},
  {t:"Ibuprofen 400 mg after food 2–3×/day for pain/swelling.", f:"nsaid"},
  {t:"After 48 h: warm compress + gentle movement; return gradually."},
  {t:"Can't bear weight / severe swelling / deformity → X-ray (fracture check)."}],
 ayur:["First 48 h stick to ice (classical too: avoid heat on fresh injury).","After 48 h: gentle warm Mahanarayana/Murivenna oil application + light bandage.","Turmeric 1/2 tsp + pinch black pepper in warm milk at night (bruise/inflammation support).","Lakshadi guggulu 1 tab twice daily if bone bruise/slow healing (practitioner)."],
 tests:["injury"], seeDoc:["Not improving in 3–4 days","Joint feels unstable/gives way","Repeated sprains"],
 emerg:["Obvious deformity/severe swelling immediately","Cannot put any weight even after rest+ice","Numbness/cold/blue toes-fingers below injury"]},

{id:"joint_pain", nm:"Joint pain (knee/arthritis type)", al:["joint pain","knee pain","ghutne dard","ghutna","arthritis","gathiya","joint stiffness"],
 sys:"musculo", doctor:"Orthopedician / rheumatologist",
 dq:[{q:"Which pattern fits?",opts:["Morning stiffness >30 min, multiple joints, swelling","Pain worse with activity, better with rest, age >45 (wear & tear)","Sudden hot red big-toe/foot joint (gout-like)","After minor injury/overuse"]}],
 modern:[
  {t:"Paracetamol 650 mg regular ×3–5 days OR ibuprofen 400 mg after food if swelling (short course).", f:"nsaid"},
  {t:"Topical diclofenac gel 3–4×/day on the joint."},
  {t:"Hot fomentation for stiffness, ice if acutely swollen; weight loss = biggest knee medicine; quadriceps strengthening daily."},
  {t:"Gout-like attack: rest, ice, fluids, avoid alcohol/red meat — see a doctor for uric-acid testing & specific medicines."}],
 ayur:["Wear-and-tear (Sandhivata): warm sesame/Mahanarayana oil massage + fomentation daily; Yogaraja guggulu 1 tab twice daily; ashwagandha with milk at night; janu basti therapy for knees.","Swelling+stiffness with heaviness (Amavata/rheumatoid-like): DON'T oil-massage initially; dry heat, light diet, dry-ginger water sips, Rasnasaptaka kwatha; needs an Ayurvedic physician.","Gout-like (Vatarakta): Kaishore guggulu 1 tab twice daily, giloy, cherry/amla; avoid alcohol, red meat.","Fenugreek 1 tsp soaked overnight each morning; turmeric-milk at night."],
 tests:["joint_chronic"],
 seeDoc:["Multiple joints with morning stiffness (rheumatoid needs early treatment — very treatable now)","Recurring gout attacks","Pain limiting daily activity (X-ray + plan)"],
 emerg:["ONE joint suddenly hot, red, very painful ± fever → same-day doctor (infection in joint is an emergency)"]},

{id:"cramps", nm:"Muscle cramps", al:["cramps","leg cramp","nas chadna","muscle cramp","charley horse","night cramps"],
 sys:"musculo", doctor:"General physician",
 modern:[
  {t:"During cramp: stretch the muscle firmly (pull toes up for calf) + massage."},
  {t:"Hydrate; add a pinch of salt+lemon water after sweating; eat a banana daily (potassium)."},
  {t:"Stretch calves before bed for night cramps; warm shower before sleep."},
  {t:"Frequent cramps → check with doctor (electrolytes, medicines like diuretics, thyroid)."}],
 ayur:["Sesame-oil massage of legs at night (Vata pacification).","Milk + soaked almonds/sesame (natural calcium-magnesium); dates.","Ashwagandha 1/2 tsp with milk at night for recurrent cramps."],
 tests:[], seeDoc:["Frequent/severe or daytime cramps","With muscle weakness/wasting","On BP/diuretic medicines"], emerg:["Calf cramp-pain with one-sided swelling/warmth (clot risk) — urgent"]},

{id:"rash", nm:"Skin rash / itching (eczema-type)", al:["rash","itching","khujli","skin allergy","eczema","dermatitis","itchy skin","daane"],
 sys:"skin", doctor:"Dermatologist",
 dq:[{q:"Which looks closest?",opts:["Dry itchy patches","Oozing/wet patches","Ring-shaped patch with clear centre (fungal)","Raised wheals that come & go (hives)","Itching all over, worse at night, family itching too (scabies-like)"]}],
 modern:[
  {t:"Moisturise generously 3–4×/day (fragrance-free) — dryness drives most itch."},
  {t:"Cetirizine 10 mg at night for itch.", f:"sed"},
  {t:"Hydrocortisone 1% cream thin layer twice daily ≤7 days on small itchy patches (NOT on face/broken skin/fungal rings).", f:""},
  {t:"Lukewarm (not hot) baths; mild soap; cotton clothing; identify trigger (new soap/detergent/metal/plant)."},
  {t:"Ring-shaped = fungal → see the fungal plan (steroid creams make fungus WORSE)."}],
 ayur:["Neem-leaf paste or neem-water bath for itchy areas.","Coconut oil (dry types) after bath; aloe vera gel for irritated skin.","Khadirarishta 15 ml with equal water after meals twice daily (classical blood-purifier for skin).","Avoid: curd+fish or milk+salty combos (viruddha ahara), excess sour/fermented food; manage constipation (skin mirrors gut).","Manjishtha or neem capsule/churna as blood purifier for recurring rashes."],
 tests:[], seeDoc:["Spreading, oozing, painful, or crusted rash (may need prescription creams)","Rash not improving in 1–2 weeks","Scabies-suspect (whole-family treatment needed — doctor confirms)"],
 emerg:["Rash with fever that doesn't fade on glass pressure","Hives with lip/throat swelling or breathlessness","Painful rapidly-spreading red skin with fever"]},

{id:"fungal", nm:"Fungal infection (ringworm/athlete's foot)", al:["fungal","ringworm","daad","dad khaj","athlete's foot","jock itch","itching groin","fungal infection"],
 sys:"skin", doctor:"Dermatologist",
 modern:[
  {t:"Clotrimazole or terbinafine cream: apply thin layer twice daily covering 2 cm BEYOND the ring edge; continue 2 WEEKS AFTER it looks cleared (total 3–4 weeks) — stopping early = relapse."},
  {t:"Keep the area DRY: change socks/innerwear daily, dry well after bath, dust antifungal powder in folds."},
  {t:"Don't share towels; wash clothes in hot water; treat family members with similar patches."},
  {t:"NEVER apply steroid creams (or 'quick-relief' combo creams) — they feed the fungus and cause resistant daad."}],
 ayur:["Apply crushed-garlic-infused coconut oil or raw turmeric paste to the patch (traditional antifungals) alongside cream.","Neem bath/wash daily; keep kapha-damp away: dry body fully.","Gandhaka rasayana (purified sulphur classical) via an Ayurvedic doctor for recurrent cases.","Cut excess sugar/curd/fermented food till clear."],
 tests:[], seeDoc:["Scalp or nail involvement (needs prescription tablets)","Widespread or recurring despite 4 weeks of correct cream","Diabetic with fungal infections (check sugar)"],
 emerg:[]},

{id:"acne", nm:"Acne / pimples", al:["acne","pimple","pimples","muhase","keel","face spots"],
 sys:"skin", doctor:"Dermatologist",
 modern:[
  {t:"Benzoyl peroxide 2.5% gel thin layer at night on affected area (start alternate nights; mild dryness normal)."},
  {t:"Gentle face wash twice daily; DON'T scrub, DON'T squeeze (scars come from squeezing)."},
  {t:"Oil-free/non-comedogenic moisturiser + sunscreen; change pillowcase often.","f":""},
  {t:"Moderate/severe or scarring → dermatologist early (very effective prescription options exist)."}],
 ayur:["Face pack: red sandalwood + turmeric pinch + rose water, 15 min, 3×/week; or multani mitti for oily skin.","Neem + turmeric water wash; don't over-dry the skin.","Triphala 1 tsp at night (gut-skin link); reduce fried/junk/excess dairy & sweets.","Kumkumadi taila few drops at night on old marks (not on active oily acne)."],
 tests:[], seeDoc:["Painful deep nodules or scarring","No improvement in 6–8 weeks","Sudden acne with irregular periods (hormonal check)"], emerg:[]},

{id:"hives", nm:"Hives (urticaria)", al:["hives","urticaria","sheetpitta","wheals","welts","sudden itchy bumps"],
 sys:"skin", doctor:"Dermatologist / allergist",
 modern:[
  {t:"Cetirizine 10 mg once daily (doctor may advise up to twice daily) till clear + 3–4 days.", f:"sed"},
  {t:"Cool compress; loose cotton clothes; avoid hot showers/scratching."},
  {t:"Hunt the trigger: new food (nuts/seafood), medicine (painkiller/antibiotic), infection, pressure/cold."},
  {t:"Recurring >6 weeks → allergist (chronic urticaria — manageable)."}],
 ayur:["Haridra khanda 1 tsp with warm milk twice daily — the classical sheetpitta remedy.","Turmeric + jaggery small ball twice daily; avoid curd, fermented, sour foods during episodes.","Apply mustard-oil lightly then warm bath (traditional); avoid cold wind exposure."],
 tests:[], seeDoc:["Episodes recurring >6 weeks","With joint pain/fever","Triggered by a medicine (note the name, tell every future doctor)"],
 emerg:["Lip/tongue/throat swelling, breathlessness, dizziness → EMERGENCY (anaphylaxis)"]},

{id:"wound", nm:"Minor cut / wound / burn", al:["cut","wound","burn","jala","chot","ghav","scrape","bleeding cut","laceration"],
 sys:"skin", doctor:"General physician / ER for deep wounds",
 modern:[
  {t:"CUT: wash hands → run clean water over wound → press with clean cloth till bleeding stops → antiseptic (povidone-iodine) → dressing. Change daily."},
  {t:"BURN: hold under cool RUNNING water 20 full minutes (no ice/toothpaste/butter) → loose non-stick dressing → paracetamol for pain.", f:"pcm"},
  {t:"Tetanus: if wound is dirty/deep/rusty-metal and last TT shot >5 yrs → get a TT injection same day."},
  {t:"Watch 48–72 h for infection: increasing redness, warmth, pus, red streaks, fever → doctor."}],
 ayur:["After bleeding stops: turmeric is the classical antiseptic — clean paste on minor scrapes.","Honey thin layer under dressing for clean shallow wounds (classical + evidence).","Aloe vera gel for healed-over burns; ghee+honey mix (classical) for minor healing wounds.","Jatyadi taila/ghrita for slow-healing minor wounds."],
 tests:[], seeDoc:["Gaping/deep cut (stitches work best within 6–8 h)","Animal/human bite (needs rabies protocol!)","Any infection signs","Diabetic with any foot wound — same day"],
 emerg:["Bleeding not stopping with 10 min firm pressure","Large/deep burn, face/hand/genital burn, electrical/chemical burn","Numbness or can't move the part"]},

{id:"eye_red", nm:"Red / itchy eye", al:["red eye","eye pain","conjunctivitis","aankh lal","eye infection","itchy eyes","eye discharge"],
 sys:"eye", doctor:"Ophthalmologist",
 dq:[{q:"Which fits?",opts:["Watery + itchy both eyes (allergy-like)","Sticky yellow discharge, lids stuck in morning","Gritty/dry feeling, screen-heavy day","Pain inside eye / vision affected"]}],
 modern:[
  {t:"Infective type spreads fast: separate towel, wash hands, no eye rubbing, no sharing cosmetics."},
  {t:"Lubricating eye drops 4–6×/day soothe all types; cold compress for allergy-itch."},
  {t:"Allergy: antihistamine drops + oral cetirizine at night.", f:"sed"},
  {t:"Sticky bacterial type: clean lids with boiled-cooled water; if not better in 2 days → doctor (antibiotic drops are prescription in most places).","f":""},
  {t:"CONTACT LENS users with red eye: remove lens, see eye doctor same day."}],
 ayur:["Triphala eyewash: steep 1 tsp overnight, strain through fine cloth VERY well, wash eyes in morning (classical netra-prakshalana).","Rose water (pure, sterile) 1–2 drops for irritation.","Palming + 20-20-20 screen breaks; ghee 1 tsp in warm milk at night (eye nourishment).","Amla daily (eye rasayana)."],
 tests:[], seeDoc:["Not improving in 2–3 days","Recurring allergy (drops that prevent exist)","Any discharge in a newborn — same day"],
 emerg:["Eye PAIN (not just irritation), vision blur/loss, halos around lights, severe headache+vomiting","Chemical splash → wash 20 min & go","Injury/foreign body embedded"]},

{id:"toothache", nm:"Toothache", al:["toothache","daant dard","tooth pain","dant","cavity pain","wisdom tooth"],
 sys:"dental", doctor:"Dentist",
 modern:[
  {t:"Ibuprofen 400 mg after food (best for dental pain) ± paracetamol 650 mg in-between if severe (don't exceed either's max).", f:"nsaid"},
  {t:"Warm salt-water rinse 3–4×/day; floss out any trapped food near the tooth."},
  {t:"Clove oil on a cotton wisp against the tooth — temporary numbing."},
  {t:"THIS IS A HOLDING PLAN: painkillers don't cure a cavity/infection — book a dentist in 1–2 days (the actual quick fix)."}],
 ayur:["Clove (laung) chewed slowly against the tooth or clove oil application — the classical remedy.","Salt + mustard-oil pinch massaged on gums; oil pulling (1 tbsp sesame/coconut oil swished 5–10 min) daily for gum health.","Neem datun / neem-based paste for gum inflammation."],
 tests:[], seeDoc:["All toothache needs a dentist — within 1–2 days","Bleeding gums routinely (gum treatment + scaling)","Sensitivity persisting"],
 emerg:["Facial/jaw swelling, fever, difficulty opening mouth or swallowing → same-day emergency (spreading infection)"]},

{id:"mouth_ulcer", nm:"Mouth ulcers", al:["mouth ulcer","muh me chala","chhala","canker sore","mouth sore","tongue ulcer"],
 sys:"dental", doctor:"Dentist / physician if recurrent",
 modern:[
  {t:"Antiseptic/anaesthetic oral gel (choline salicylate or lidocaine-based) on ulcer 3–4×/day before food."},
  {t:"Warm salt-water rinses; avoid spicy/acidic/rough food till healed (7–10 days natural course)."},
  {t:"B-complex once daily for 2 weeks if recurrent (common deficiency link)."}],
 ayur:["Honey + pinch of turmeric dabbed on ulcer 3×/day.","Chew 1–2 fresh guava leaves or apply glycerin; licorice piece to suck.","Triphala water swish twice daily; treat constipation (classic Pitta-gut link); coconut water, avoid very hot food."],
 tests:[], seeDoc:["Any single ulcer lasting >3 weeks (MUST be checked — cancer rule-out, esp. tobacco users)","Large/multiple recurrent crops (deficiency/other checks)","With eye/genital sores or joint pain"],
 emerg:[]},

{id:"insomnia", nm:"Poor sleep (insomnia)", al:["insomnia","neend nahi","can't sleep","sleep problem","sleeplessness","no sleep"],
 sys:"mental", doctor:"Physician / sleep specialist",
 modern:[
  {t:"Sleep hygiene (works better than pills): fixed wake time daily, no screens 1 h before bed, dark cool room, caffeine only before 2 pm, no daytime naps >20 min, bed = only for sleep."},
  {t:"If not asleep in ~20 min: get up, do something boring in dim light, return sleepy."},
  {t:"Exercise 30 min daily (not within 3 h of bed)."},
  {t:"Melatonin 3 mg 1 h before bed short-term (jet-lag/shift); avoid nightly sedative dependence — if >3–4 weeks, see a doctor (CBT-I is the gold standard)."}],
 ayur:["Warm milk + pinch of nutmeg (jaiphal) at bedtime — classical sleep inducer.","Warm sesame-oil massage to soles & scalp before bath/bed.","Ashwagandha 1/2 tsp with milk at night; Brahmi or jatamansi tea in the evening.","Bhramari pranayama (humming breath) 5 min + left-nostril breathing at bedtime; early light dinner."],
 tests:["chronic_fatigue"],
 seeDoc:["Beyond 3–4 weeks or affecting daytime function","Loud snoring with breath pauses (sleep apnea — treatable)","With low mood/anxiety (treat the cause)"],
 emerg:["Sleeplessness with racing thoughts of self-harm → crisis help now"]},

{id:"anxiety", nm:"Stress / anxiety", al:["anxiety","tension","stress","ghabrahat","panic","worry","chinta","restless"],
 sys:"mental", doctor:"Psychiatrist / psychologist",
 modern:[
  {t:"Slow breathing NOW: inhale 4s – hold 4s – exhale 6-8s × 10 rounds (physiologically lowers the alarm)."},
  {t:"Daily: 30-min brisk walk, fixed sleep, cut caffeine/alcohol, limit doom-scrolling."},
  {t:"Name it & schedule it: 15-min daily 'worry window' + write the worries down."},
  {t:"Persistent (>2–4 weeks), panic attacks, or interfering with life → therapist/psychiatrist (therapy + short-term medicines work very well; nothing to be ashamed of)."}],
 ayur:["Ashwagandha 300–500 mg (or 1/2 tsp churna with milk) twice daily — the prime adaptogen; 6–8 weeks course.","Brahmi tea/ghee morning; jatamansi at night for sleep-linked anxiety.","Daily abhyanga (warm-oil self massage) + shirodhara series for deep-set stress.","Anulom-vilom & bhramari pranayama 10 min morning; sattvic diet, fixed routine (Vata thrives on rhythm)."],
 tests:["chronic_fatigue"],
 seeDoc:["Symptoms >2–4 weeks or worsening","Panic attacks","With palpitations/weight change (thyroid check)"],
 emerg:["Chest pain + sweating + breathlessness — rule out heart FIRST, don't assume anxiety","Thoughts of self-harm → crisis line now (India: 9152987821 / 14416)"]},

{id:"dandruff", nm:"Dandruff / hair fall", al:["dandruff","hair fall","hairfall","balo ka girna","rusi","hair loss","itchy scalp"],
 sys:"skin", doctor:"Dermatologist",
 modern:[
  {t:"Ketoconazole 2% shampoo twice weekly (lather, LEAVE 5 min, rinse) × 4 weeks, then weekly maintenance; normal shampoo other days."},
  {t:"Hair fall basics: check & fix iron/B12/vitamin-D/thyroid (simple blood tests); protein in every meal; gentle handling, no tight hairstyles."},
  {t:"Minoxidil (OTC) only after a dermatologist confirms pattern hair loss — commit ≥6 months."},
  {t:"Post-illness/postpartum shedding usually self-recovers in 3–6 months."}],
 ayur:["Bhringraj or coconut-amla oil: warm, massage scalp 2–3×/week, wash after 1 h (not overnight if dandruff).","Amla daily (1 fresh / 1 tsp powder / murabba) — the classical hair rasayana.","Triphala at night; adequate sleep (hair = asthi-majja byproduct; stress shows in hair).","Neem-water rinse for itchy scalp; avoid excessive hot-water on head (classical caution)."],
 tests:["chronic_fatigue","anemia_suspect"],
 seeDoc:["Patchy coin-shaped bald spots (alopecia areata — treatable, see derm early)","Scarring/painful scalp","Sudden diffuse shedding continuing >6 months"], emerg:[]},

{id:"sugar_query", nm:"High sugar / diabetes concern", al:["diabetes","sugar","blood sugar","madhumeh","sugar high","hba1c","excess thirst urination"],
 sys:"chronic", doctor:"Physician / diabetologist",
 modern:[
  {t:"Get tested rather than guess: fasting + post-meal sugar and HbA1c (any lab, ~no doctor needed for the test)."},
  {t:"Diagnosed ranges: Fasting ≥126 or HbA1c ≥6.5 = diabetes; 100–125 / 5.7–6.4 = prediabetes (reversible window!)."},
  {t:"Whatever the number: 30-min daily walk (esp. after meals), plate = ½ vegetables, stop sugary drinks, sleep 7–8 h, lose 5–7% weight if overweight.","f":""},
  {t:"Diabetes management medicines are prescription — a physician will personalise; NEVER stop prescribed medicines for any alternative therapy; monitor sugar if adding herbs (they add to the effect)."}],
 ayur:["Adjuncts with doctor's knowledge: fenugreek 1 tsp soaked overnight (morning), bitter-gourd (karela) juice 20 ml morning, amla+turmeric (Nishamalaki) 1 tsp twice daily, jamun seed powder 1/2 tsp.","Gudmar (Gymnema) 500 mg twice daily — the classical 'sugar-destroyer' (monitor sugars).","Barley-based meals (classical prameha staple); daily exercise is non-negotiable in Ayurveda too.","Avoid: sugarcane products, excess dairy/sweets/new grains, day-sleep (classical apathya)."],
 tests:["sugar_suspect"],
 seeDoc:["Any confirmed high reading → physician for full plan","Existing diabetic with sugars out of range","Numb feet, blurred vision, non-healing wounds (complication screening)"],
 emerg:["Very high sugar with vomiting/rapid breathing/drowsiness","Sweating/shaking/confusion (LOW sugar — give sugar/glucose immediately if conscious)"]},

{id:"bp_query", nm:"High blood pressure concern", al:["bp","blood pressure","hypertension","high bp","bp high"],
 sys:"chronic", doctor:"Physician / cardiologist",
 modern:[
  {t:"Measure properly: seated, rested 5 min, arm supported — twice daily × 1 week (home machine/pharmacy). One reading ≠ diagnosis."},
  {t:"≥140/90 repeatedly → physician (medicines are prescription and very effective). 180/120 or higher → urgent same-day."},
  {t:"What actually lowers BP: salt <5 g/day (skip papad/pickle/processed), 30-min daily walk, weight loss, stop smoking, limit alcohol, sleep, stress work.","f":""},
  {t:"NEVER stop prescribed BP medicines abruptly."}],
 ayur:["Adjuncts: garlic 1 clove morning, arjuna bark tea/capsule (heart tonic), brahmi/jatamansi for stress component.","Shirodhara + daily meditation/pranayama (anulom-vilom, bhramari) have measurable BP benefit.","Sarpagandha is the classical BP herb but ONLY under an Ayurvedic physician (interactions/depression risk).","Reduce salty-sour-fried; favour lauki, coconut water, amla."],
 tests:[], seeDoc:["Repeated readings ≥140/90","Already on medicines but uncontrolled","BP high in pregnancy — urgent"],
 emerg:["≥180/120 with headache/chest pain/vision change/breathlessness → EMERGENCY","BP high + one-sided weakness/slurred speech → stroke protocol"]},

{id:"weight", nm:"Weight management", al:["weight loss","obesity","motapa","weight gain","fat loss","overweight"],
 sys:"chronic", doctor:"Physician / dietitian",
 modern:[
  {t:"Target 0.5 kg/week: ~500 kcal daily deficit. Protein at every meal (dal/paneer/eggs/curd) — controls hunger."},
  {t:"Walk 8–10k steps daily + 2×/week strength work; sleep 7–8 h (short sleep = weight gain hormone-wise)."},
  {t:"Stop liquid calories (sugary tea/coffee/colas/juice); half-plate vegetables; eat within a ~10–12 h window."},
  {t:"Rule out thyroid/PCOS/medicines if weight gain is unexplained (simple tests). Crash diets & 'fat-burner' pills: avoid."}],
 ayur:["Warm honey-lemon water morning (traditional kapha-melter) + udvartana (dry powder massage) weekly.","Triphala 1 tsp at night; Trikatu (dry ginger+pepper+pippali) pinch with honey before lunch to raise agni.","Barley/millet meals over rice at night; no day-sleep after meals (classical apathya for sthaulya).","Guggul-based classical formulas (Navaka guggulu) via an Ayurvedic doctor; exercise is core in both systems."],
 tests:["chronic_fatigue","sugar_suspect"],
 seeDoc:["BMI ≥30 or weight-related symptoms (structured program)","Unexplained rapid weight change either way (thyroid etc.)"], emerg:[]},

{id:"fatigue", nm:"Weakness / tiredness", al:["weakness","fatigue","tired","kamzori","thakan","low energy","always tired"],
 sys:"general", doctor:"General physician",
 modern:[
  {t:"Get the basic 5 tests (very often one is the answer): CBC (anaemia), TSH (thyroid), fasting sugar, Vitamin D, B12."},
  {t:"Sleep 7–8 h fixed schedule; 20-min daily walk actually RAISES energy; hydrate; protein each meal."},
  {t:"Review: crash diets, skipped meals, heavy periods (women), snoring (apnea), low mood (depression fatigue is real and treatable)."}],
 ayur:["Ashwagandha 1/2 tsp with warm milk at night × 6–8 weeks — prime strength rasayana.","Chyawanprash 1 tsp morning with warm milk.","Dates + soaked almonds + milk breakfast addition; amla daily.","Abhyanga (oil massage) 2–3×/week; pranayama morning; don't suppress hunger/sleep (classical vega rules)."],
 tests:["chronic_fatigue","anemia_suspect","sugar_suspect"],
 seeDoc:["Tiredness >2–3 weeks despite sleep & food fixes → test, don't guess","With breathlessness on stairs, pale nails (anaemia)","With weight change/cold intolerance (thyroid)"],
 emerg:["Sudden severe weakness one side of body","Fainting spells","Breathlessness at rest"]},

{id:"generic", nm:"General health concern", al:[],
 sys:"general", doctor:"General physician",
 modern:[
  {t:"From what you've told me, this doesn't cleanly match a common quick-fix pattern — and guessing would be bad medicine."},
  {t:"Comfort measures: rest, hydration, light food, paracetamol 650 mg after food if there's pain/fever (max 4/day).", f:"pcm"},
  {t:"Track: when it started, what worsens/relieves it, any fever, appetite/weight/sleep changes — this record makes the doctor visit twice as useful."}],
 ayur:["Light, warm, freshly-cooked food; avoid heavy/fried/cold items till clear.","Ginger-tulsi tea twice daily; early dinner, proper sleep.","Triphala 1 tsp at night if digestion feels off (most issues start in the gut per Ayurveda)."],
 tests:[], seeDoc:["If it persists beyond 3–5 days, worsens, or worries you — see a physician; carry your symptom notes"],
 emerg:["Any red-flag symptom listed at the end of this report"]}
]};
const DB_PAIN_MAP = {head:["headache","migraine"], eyes:["eye_red"], ear:["earache"], throat:["sore_throat","cold"], chest:["CHEST_SPECIAL"], upabd:["acidity","indigestion","stomach_pain"], lowabd:["uti","period_pain","constipation","stomach_pain"], back:["back_pain"], joints:["joint_pain","sprain"], muscles:["cramps","fatigue","flu"], skin:["rash","fungal","hives","wound"], urinary:["uti"], teeth:["toothache","mouth_ulcer"]};
